steps:

- name: eu.gcr.io/energia-cloud-widget/energia-europa-minifier:latest
  env:
    - 'DIRECTORY=/workspace'

- name: alpine
  entrypoint: "sh"
  args:
  - "-c"
  - |
    mv ./lib ./$TAG_NAME

- name: alpine
  entrypoint: "sh"
  args:
  - "-c"
  - |
    find ./ | grep -oEi ".*\.(php|git)" | while read -r file ; do
        rm -rf "$file"
    done

- name: gcr.io/cloud-builders/gsutil
  args:
  - "cp"
  - "-r"
  - "./"
  - "gs://public.energia-europa.com/daily"

- name: gcr.io/cloud-builders/gsutil
  args:
  - "setmeta"
  - "-h"
  - "Content-Type:text/javascript"
  - "-r"
  - "gs://public.energia-europa.com/daily/**.js"
